import Head from "next/head";
import Header from "../components/Headers/Header";
import Nav from "../components/Headers/Nav";
import Results from "../components/main/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>En-Surf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/en-surf-logo.png" />
      </Head>

      {/* Header Component */}
      <Header />
      {/* Navigation Component NavBar */}
      <Nav />
      {/* Main Component / Results */}
      <Results items={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
